# Generated by Django 4.1.5 on 2023-04-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Image",),
    ]
